# 넘파이(Numpy)
    - 파이썬을 활용한 데이터 분석에서 가장 기본이 되는 라이브러리
    - 넘파이로만으로도 많이 사용되지만, 판다스(pandas), 머신러닝 들 수많은 분야에서   
    기본적으로 사용되므로 파이썬 개발자의 필수 라이브러리이다.

[넘파이 공식 문서](https://numpy.org/)

### 1) 수학 수치연산(numerical python)
    - 합, 평균, 행렬연산 등이 가능하다
### 2) 기본 타입
    - ndarray (n-dimenstional array) 다차원 배열의 표현
### 3) 파이썬 list가 있음에도 필요한 이유
    - 성능 : 성능적으로 훨씬 빠르다
    - 메모리 : 적은 메모리를 사용한다
    - 제공함수 : 선형대수, 통계관련 여러 수치 함수를 제공한다
    - 그 외 수 많은 모듈에서 numpy 함수명과 기능을 그대로 사용 가능하다

<img src="https://media.licdn.com/dms/image/v2/D4E22AQFKQ93ywmSGsg/feedshare-shrink_800/B4EZ.vxZJAHoAg-/0/1785360388974?e=2147483647&v=beta&t=qutjb0gyTs5FKZTWL_mxm1Xd_q22lPtZFuOiM5EAb5U" width="800"/>

In [ ]:
# 행 = []의 수, 열 = [] 안의 원소 개수

In [1]:
import numpy as np

In [3]:
arr1 = np.ndarray([1,2,3])
arr1 = np.array([1,2,3])
print(arr1)
print(type(arr1))

[1 2 3]
<class 'numpy.ndarray'>


In [35]:
# 하나의 타입으로만 정의할 수 있음.
arr2 = np.array([      1,2,3.0])

print(arr2)
print([1,2,3.0])

[1. 2. 3.]
[1, 2, 3.0]


In [36]:
arr3 = np.array([1,2,False,"홍길동", 12.5])

In [37]:
print(arr3)
# -> 넘파이의 타입 강제 승격
print(type(arr3))

['1' '2' 'False' '홍길동' '12.5']
<class 'numpy.ndarray'>


In [38]:
arr3 = np.array([i+1 for i in range(10)])
arr3
# 로우백터

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## ndarray의 인덱싱

In [39]:
print(arr3[1])
print(type(arr3[1]))
print(2)
print(type(2))
# 타입이 다름

2
<class 'numpy.int64'>
2
<class 'int'>


## ndarray의 슬라이싱

In [40]:
print(arr3[2:5])
print(arr3[::2])

[3 4 5]
[1 3 5 7 9]


### shape
    - numpy에서는 해당 array의 크기를 알 수 있다. shape를 확인함으로서, 몇 개의 데이터가 있는지 몇 차원으로 존재하는지 확인할 수 있다.
    - arr.shape의 결과는 튜플로 (행, 열)로 행만 존재하면 1차원, 행렬이 존재하면 2차원으로 차수를 알 수 있다. 또한 행*렬을 곱하면 크기도 확인할 수 있다.

In [41]:
print(arr3.shape)
# -> 1차원, 행의 10개 데이터

(10,)


In [42]:
arr4 = np.array([[2]])
arr4

array([[2]])

In [43]:
print(arr4.shape)
# 2차원 데이터이지만 scalar임.

(1, 1)


In [44]:
arr5 = np.array([[1,2,3],[4,5,6]])
print(arr5)
print(arr5.shape)

# 메트릭스
# 2행 3열(2차원)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [45]:
arr6 = np.array([[[1,2,3],[4,5,6]]])
print(arr6)
print(arr6.shape)

# 텐서
# 2행3열 메트릭스 1개(3차원)

[[[1 2 3]
  [4 5 6]]]
(1, 2, 3)


In [46]:
arr7 = np.array([
        [
            [10, 20, 30, 40],
            [50, 60, 70, 80],
            [90, 100, 110, 120],
        ],
        [
            [100, 200, 300, 400],
            [500, 600, 700, 800],
            [900, 1000, 1100, 1200],
        ],
    ])
print(arr7)
print(arr7.shape)

# 텐서
# 3행 4열 데이터 2개(3차원)

[[[  10   20   30   40]
  [  50   60   70   80]
  [  90  100  110  120]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 1100 1200]]]
(2, 3, 4)


In [47]:
arr7.ndim
# 차원수를 알려줌

3

In [48]:
arr7.size
# 데이터의 개수

24

---

## np.arange()

In [2]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.array(list(range(5,10,2)))

array([5, 7, 9])

In [5]:
np.arange(5,10,2)

array([5, 7, 9])

In [7]:
arr1 = np.arange(10)

print(arr1[6])

6


In [10]:
arr2 = np.arange(10, dtype=np.uint8)
# uint8: int64는 8비트인데, 원래는 비트 1개를 부호에 할당함. 그러나 uint는 부호가 없으므로 양수로 더 큰 숫자까지 표현 가능
# ex) int8 -> -127 ~ 127 표현 가능 / uint8 -> 0 ~ 255 표현 가능

## 넘파이의 자료형
- int: 부호가 있는 정수(8, 16, 32, 64)
- uint: 부호가 없는 정수(8, 16, 32, 64)
- float: 실수(16, 32, 64, 128)
- complex: 복소수(64, 128, 256)(자주 안 씀)
- bool: 불리언(8)
- string_: 문자열(8)(자주 안 씀)
- object: 오브젝트(64)

## astype(타입)
- 기존의 배열을 복사하고 타입을 변경하고 싶을 때

In [11]:
arr2 = np.arange(10)

print(arr2.dtype)

int64


In [13]:
arr3 = arr2.astype(np.int8)
print(arr3.dtype)
print(arr2.dtype)

int8
int64


## np.reshape()
- ndarray의 형태와 차원을 바꾸기 위해서 사용하는 메서드

In [15]:
arr3 = np.arange(12)

print(arr3.ndim)
print(arr3.shape)

1
(12,)


In [16]:
arr3.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
arr3.reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [19]:
arr3.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
arr3.reshape(2,1,2,3)

array([[[[ 0,  1,  2],
         [ 3,  4,  5]]],


       [[[ 6,  7,  8],
         [ 9, 10, 11]]]])

In [20]:
# reshape 개수 != 데이터 개수 -> 오류

In [22]:
arr4 = np.arange(24).reshape(2,6,2)
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]])

## np.ones(), np.zeros()
- ndarray의 초기값을 0 또는 1로 설정하기 위한 메서드

In [24]:
arr5 = np.ones(8)
print(arr5)
print(type(arr5[0]))

[1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.float64'>


In [27]:
arr6 = np.zeros(8)
print(arr6)
print(type(arr6[0]))

arr6 = np.zeros(8, dtype=np.int64)
print(arr6)
print(type(arr6[0]))

[0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.float64'>
[0 0 0 0 0 0 0 0]
<class 'numpy.int64'>


In [28]:
arr6 = np.zeros(64, dtype=np.int64)
print(arr6)
print(type(arr6[0]))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
<class 'numpy.int64'>


In [29]:
arr6.reshape(16,4)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [30]:
arr6.reshape(2,2,16)

array([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

## np.random
- rand: 0 ~ 1 사이의 균일 분포
- randn: 정규분포
- randint: 균일 분포 정규 난수

<img src="https://thebook.io/img/080263/218.jpg" />

In [35]:
np.random.randn(5)

array([ 1.52033776,  0.19279296, -0.1592837 ,  0.6930475 , -0.91562975])

In [36]:
np.random.randn(1)

array([0.50683825])

In [58]:
#0~4 사이의 난수
np.random.randint(5)


3

In [80]:
np.random.randint(50, 101)

87

In [82]:
np.random.randint(1,46,(2,3))

array([[15, 15, 33],
       [12, 13,  9]], dtype=int32)

## seed()
- 난수를 예측가능하도록 만들며, 실행할 때마다 동일한 난수를 발생시켜, 코드의 재현성, 특정 알고리즘의 결과를 재현하게 만든다. 
    또한 해당 알고리즘의 결과의 오류를 추적하기 위해 사용된다.

In [86]:
np.random.seed(4885)

np.random.randint(10, size=(2,5))

array([[9, 1, 0, 3, 4],
       [8, 7, 4, 7, 6]], dtype=int32)

In [98]:
np.random.seed(4885)

#0~1 균등분포
np.random.rand(10)

array([0.21350835, 0.56504926, 0.7597468 , 0.05666448, 0.6753598 ,
       0.36138766, 0.01299493, 0.04721084, 0.26603997, 0.8042786 ])

## unique()
- ndarray의 중복값을 제거해주는 함수

In [102]:
np.unique([31,11,21,11,11])

array([11, 21, 31])

## shape 변경
## ravel(), np.ravel
- 다차원 배열을 1차원으로 변경하는 메서드

In [106]:
arr7 = np.arange(24).reshape(2,3,4)
arr7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [105]:
arr7.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [107]:
# C: row 방향
arr7.ravel(order="C")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [109]:
# F: column 방향 (axis(축): -1)
# axis 0 = x축(행), axis 1 = y축(열)
arr7.ravel(order="F")

array([ 0, 12,  4, 16,  8, 20,  1, 13,  5, 17,  9, 21,  2, 14,  6, 18, 10,
       22,  3, 15,  7, 19, 11, 23])

## np.flatten()
- copy를 생성하고 원본 배열을 변경하지 않는 복사본을 반환한다.

In [112]:
arr7 = np.arange(24).reshape(2,3,4)
print(arr7)
print(arr7.flatten())

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [118]:
# -1 : 차원 유추(숫자가 커져서 reshape를 위한 계산이 힘들 때 -1 넣으면 자동 계산), -1은 한 개만 사용 가능
arr8 = np.arange(120).reshape(2, -1 ,12)
arr8

## 차원 확장
- np.expand_dims()
- axis로 지정된 축을 확장시키는 메서드

In [120]:
arr8 = np.arange(10)
print(arr8.shape)

(10,)


In [125]:
arr9 = np.expand_dims(arr8, axis=0)
print(arr9)
print(arr9.shape)

[[0 1 2 3 4 5 6 7 8 9]]
(1, 10)


In [126]:
arr9 = np.expand_dims(arr8, axis=1)
print(arr9)
print(arr9.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


## 차원 축소
- squeeze(), np.squeeze()

In [129]:
print(arr9)
print(arr9.squeeze())

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 2 3 4 5 6 7 8 9]


## 전치 행렬(transpose), T

In [130]:
# 2,3 -> 3,2
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [131]:
np.transpose(arr1)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [132]:
np.arange(15).reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [134]:
arr2 = np.arange(12).reshape(2,6)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [135]:
print(arr2.T)

[[ 0  6]
 [ 1  7]
 [ 2  8]
 [ 3  9]
 [ 4 10]
 [ 5 11]]


In [138]:
print(arr2.flatten())
print(arr2.T.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  6  1  7  2  8  3  9  4 10  5 11]


## array 간 연산

In [141]:
# 리스트 간의 연산
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [142]:
# array(2차원) + scalar(0차원)
arr1 + 10

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [143]:
# array(2차원) + scalar(1차원)
arr1 + [10]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [144]:
# array(2차원) + scalar(2차원)
arr1 + [[10]]

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [146]:
# array(2차원) + scalar(3차원)
arr1 + [[[10]]]

array([[[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]])

## 브로드캐스팅
- 다른 크기의 배열들 간에도 자동으로 연산해주는 Numpy의 강력한 기능

## 브로드캐스팅의 특징
    - 기본적으로는 shape와 같은 두 ndarray에 대한 연산은 각 원소별로 진행한다
    - 다른 shape를 갖는 array 간의 연산의 경우 브로드 캐스팅(shape를 맞춤) 후 진행한다

<img width=500 src='https://www.astroml.org/_images/fig_broadcast_visual_1.png' />

In [149]:
arr1 = np.arange(12).reshape(4,3)
print(arr1)

print(arr1.shape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
(4, 3)


In [151]:
arr2 = np.arange(3)

print(arr2)
print(arr2.shape)

[0 1 2]
(3,)


In [152]:
print(arr1 + arr2)

[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


## 브로드 캐스팅의 규칙
1. 뒷 차원부터 비교한다.
2. shape가 같아야 한다.
3. 차원 중 값이 1인 차원이 존재해야 한다.

[브로드캐스팅 공식문서](https://numpy.org/doc/stable/user/basics.broadcasting.html)

In [153]:
"""
    차원에 1이 존재하는 경우 확장이 가능하다.
    6 * 1 * 5
        7 * 3

    6 * 7 * 5
"""

None

In [154]:
arr1 = np.arange(100,104)
print(arr1)

[100 101 102 103]


In [155]:
# (4,3)
arr2 = np.arange(12).reshape(4,3)
print(arr2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [156]:
# arr1 + arr2 -> error

ValueError: operands could not be broadcast together with shapes (4,) (4,3) 

<img src="https://numpy.org/doc/stable/_images/broadcasting_3.png" />

In [163]:
# (2,3), (3,2)
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(100,106).reshape(3,2)

print(arr3)
print(arr4)

[[0 1 2]
 [3 4 5]]
[[100 101]
 [102 103]
 [104 105]]


In [164]:
# arr3 + arr4 -> error

In [165]:
arr3.T + arr4

array([[100, 104],
       [103, 107],
       [106, 110]])

In [ ]:
# (1,6), (3,2)
arr3 = np.arange(6).reshape(1,6)
arr4 = np.arange(100,106).reshape(3,2)

print(arr3)
print(arr4)

In [ ]:
# arr3 + arr4 -> error

## 차원축(axis)
- 1차원 array라면 각 차원에 대한 axis 값은 0
- 2차원 array라면 각 차원에 대한 axis 값은 0,1
- 3차원 array라면 각 차원에 대한 axis 값은 0,1,2

In [168]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [169]:
np.sum(arr1)

np.int64(105)

In [175]:
# arr1의 axis 0에 있는 값들끼리 더함.
np.sum(arr1, axis=0)

array([15, 18, 21, 24, 27])

In [176]:
arr1 = np.arange(15).reshape(3,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [177]:
np.sum(arr1, axis=0)

array([15, 18, 21, 24, 27])

In [178]:
np.sum(arr1, axis=1)

array([10, 35, 60])

In [180]:
arr2 = np.arange(24).reshape(2,3,4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [181]:
np.sum(arr2, axis=0)

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [182]:
np.sum(arr2, axis=-1)

array([[ 6, 22, 38],
       [54, 70, 86]])

In [183]:
arr2.shape

(2, 3, 4)

## ※argmax()※
- 최대값의 인덱스

In [187]:
arr3 = np.arange(5,10)
print(arr3)
print(list(enumerate(arr3)))
print(arr3.argmax())
print(arr3[arr3.argmax()])

[5 6 7 8 9]
[(0, np.int64(5)), (1, np.int64(6)), (2, np.int64(7)), (3, np.int64(8)), (4, np.int64(9))]
4
9


In [197]:
np.random.seed(918)
arr4 = np.random.randint(10,size=(1,6)).flatten()
print(list(enumerate(arr4)))
print(arr4.argmax())
print(arr4.max())
print(arr4.argmin())
print(arr4.min())

print(np.argmax(arr4))

[(0, np.int32(9)), (1, np.int32(3)), (2, np.int32(3)), (3, np.int32(4)), (4, np.int32(2)), (5, np.int32(5))]
0
9
4
2
0


In [198]:
arr5 = np.random.randint(10,size=(3,6))
arr5

array([[0, 6, 5, 0, 8, 5],
       [3, 4, 6, 8, 1, 8],
       [4, 8, 2, 3, 7, 7]], dtype=int32)

In [199]:
print(arr5.argmax(axis=0))

[2 2 1 1 0 1]


In [200]:
print(arr5.argmax(axis=1))

[4 3 1]


In [204]:
print(arr5.max(axis=0))
print(arr5.max(axis=1))

[4 8 6 8 8 8]
[8 8 8]


In [205]:
print(arr5.min(axis=0))
print(arr5.min(axis=1))

[0 4 2 0 1 5]
[0 1 2]


## boolean selection(=boolean indexing)
- array 인덱싱 시, bool 타입의 조건에 맞는 list를 전달하여 조건식을 만족하는 True의 결과물만 필터링한다.

In [207]:
arr4 = np.random.randint(1,100,size=(20))
print(arr4)

[41 46 37 42 36 92  3 70 95 75  4 32 31 86 18 47 84 23 44 88]


In [213]:
arr4[arr4 % 2 == 0]

array([46, 42, 36, 92, 70,  4, 32, 86, 18, 84, 44, 88], dtype=int32)

In [215]:
arr4 % 2 == 0

array([False,  True, False,  True,  True,  True, False,  True, False,
       False,  True,  True, False,  True,  True, False,  True, False,
        True,  True])

In [212]:
even_mask = arr4 % 2 == 0
arr4[even_mask]

array([46, 42, 36, 92, 70,  4, 32, 86, 18, 84, 44, 88], dtype=int32)

In [214]:
is_bound = arr4 > 30
is_bound

array([ True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False,  True,  True,  True, False,  True,  True, False,
        True,  True])

## 다중 조건식
- & : and 조건식
- | : or 조건식

In [219]:
# 홀수이면서 50보다 작은 값
# and 조건 필요
np.random.seed(2026)

arr5 = np.random.randint(100, size=15)
arr5

array([ 1,  6, 26, 56, 77, 77, 29, 28, 51, 69, 76, 28,  2, 54, 77],
      dtype=int32)

In [221]:
is_bound = (arr5 % 2 != 0) & (arr5 < 50)
arr5[is_bound]

array([ 1, 29], dtype=int32)

In [223]:
arr5[is_bound].astype(str)

array(['1', '29'], dtype='<U11')